using System.Numerics;
using System.Reflection;

namespace TooString.Specs;

struct AStruct { public string A {get; init; } public Complex B { get; init; } }

[TestFixture]
public class TooStringReflectionOptionCSharpReturnsCSharp
{
    internal static readonly HttpClient httpClient = new HttpClient() { BaseAddress = new Uri("http://127.0.0.1") };

    [TestCase(null, "null")]
    [TestCase("boo", "boo")]
    [TestCase(1, "1")]
    [TestCase(1.2f, "1.2")]
    [TestCase(1.2d, "1.2")]
    [TestCase(UriKind.Absolute,"Absolute")]
    public void GivenAScalar(object value, string expected)
    {
        Assert.That(value.TooString(TooStringMethod.Reflection ), Is.EqualTo(expected));
    }
    
    [Test]
    public void GivenStruct()
    {
        //var value = new KeyValuePair<int, string>(1, "boo");
        var value = new AStruct { A = "boo", B = new Complex(3, 4) };
        Assert.That(value.TooString(TooStringMethod.Reflection ), Is.EqualTo(value.ToString()));
    }
    
    [Test]
    public void GivenAnonymousObject()
    {
        var value = new {
                one=1, 
                two="boo", 
                three=false, 
                four=UriKind.Absolute, 
                five= new CompositeA{A = "A", B= new Complex(3,4)}
            };
        Assert.That(value.TooString(TooStringMethod.Reflection ), Is.EqualTo(value.ToString()));
    }
    
    [Test]
    public void GivenTuple()
    {
        var value = (1,"boo",false,UriKind.Absolute);
        Assert.That(value.TooString(TooStringMethod.Reflection ), Is.EqualTo(value.ToString()));
    }
    
    [Test]
    public void GivenNamedTuple()
    {
        var value = (one:1, two:"boo", three:false, four:UriKind.Absolute, five: new CompositeA{A = "A", B= new Complex(3,4)});
        Assert.That(value.TooString(TooStringMethod.Reflection ), Is.EqualTo(value.ToString()));
    }
    
    [Test]
    public void GivenACompositeObject()
    {
        var value = new CompositeA { A = "boo", B = new Complex(3,4) };
        var expected = 
            """
            { A = boo, B = { Real = 3, Imaginary = 4, Magnitude = 5, Phase = 0.9272952180016122 } }
            """;
        
        Assert.That(
            value.TooString(TooStringMethod.Reflection,SerializationStyle.DotNetDebug,""), 
            Is.EqualTo(expected) 
        );
    }
    
    [Test]
    public void WithCircularReferencesNulledOut__GivenCircularReferences()
    {
        var value = new Circular{ A = "boo"};
        value.B = value;
        var expected = 
            "{\"A\":\"boo\",\"B\":null}";
        
        Assert.That(
            value.TooString(TooStringMethod.Reflection), 
            Is.EqualTo(expected) 
        );
    }
    
    [Test,Ignore("Don't create an HttpClient on every test run")]
    public void GivenDifficultObject()
    {
        var value = httpClient;
        var expected = 
            "{\"DefaultRequestHeaders\":[],\"DefaultRequestVersion\":\"1.1\"," +
            "\"DefaultVersionPolicy\":0,\"BaseAddress\":\"http://127.0.0.1\"," +
            "\"Timeout\":\"00:01:40\",\"MaxResponseContentBufferSize\":2147483647}";
        
        Assert.That(
            value.TooString(TooStringMethod.Reflection), 
            Is.EqualTo(expected) 
        );
    }
    
    [Test]
    public void GivenAnUnJsonableReflectionType_Assembly()
    {
        var value = Assembly.GetExecutingAssembly();

        var expected = """
                       { CodeBase = file:///Users/chris/Source/Repos/TestBase/TooString.Specs/bin/Debug/net6.0/TooString.Specs.dll, FullName = TooString.Specs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, EntryPoint = { Name = Main, DeclaringType = AutoGeneratedProgram, ReflectedType = AutoGeneratedProgram, MemberType = Method, MetadataToken = 100663317, Module = TooString.Specs.dll, IsSecurityCritical = True, IsSecuritySafeCritical = False, IsSecurityTransparent = False, MethodHandle = System.RuntimeMethodHandle, Attributes = PrivateScope, Private, Static, HideBySig, CallingConvention = Standard, ReturnType = System.Void, ReturnTypeCustomAttributes = Void, ReturnParameter = Void, IsCollectible = False, IsGenericMethod = False, IsGenericMethodDefinition = False, ContainsGenericParameters = False, MethodImplementationFlags = Managed, IsAbstract = False, IsConstructor = False, IsFinal = False, IsHideBySig = True, IsSpecialName = False, IsStatic = True, IsVirtual = False, IsAssembly = False, IsFamily = False, IsFamilyAndAssembly = False, IsFamilyOrAssembly = False, IsPrivate = True, IsPublic = False, IsConstructedGenericMethod = False, CustomAttributes = [] }, DefinedTypes = { Length = 19, LongLength = 19, Rank = 1, SyncRoot = [], IsReadOnly = False, IsFixedSize = True, IsSynchronized = False }, IsCollectible = False, ManifestModule = { MDStreamVersion = 131072, FullyQualifiedName = /Users/chris/Source/Repos/TestBase/TooString.Specs/bin/Debug/net6.0/TooString.Specs.dll, ModuleVersionId = f12d29e1-be9f-4aa1-be74-3978ad26b048, MetadataToken = 1, ScopeName = TooString.Specs.dll, Name = TooString.Specs.dll, Assembly = TooString.Specs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ModuleHandle = System.ModuleHandle, CustomAttributes = System.Collections.ObjectModel.ReadOnlyCollection`1[System.Reflection.CustomAttributeData] }, ReflectionOnly = False, Location = /Users/chris/Source/Repos/TestBase/TooString.Specs/bin/Debug/net6.0/TooString.Specs.dll, ImageRuntimeVersion = v4.0.30319, GlobalAssemblyCache = False, HostContext = 0, IsDynamic = False, ExportedTypes = { Length = 4, LongLength = 4, Rank = 1, SyncRoot = [], IsReadOnly = False, IsFixedSize = True, IsSynchronized = False }, IsFullyTrusted = True, CustomAttributes = { Count = 10, Item = "cantretrievevalue" }, EscapedCodeBase = file:///Users/chris/Source/Repos/TestBase/TooString.Specs/bin/Debug/net6.0/TooString.Specs.dll, Modules = { Length = 1, LongLength = 1, Rank = 1, SyncRoot = [], IsReadOnly = False, IsFixedSize = True, IsSynchronized = False }, SecurityRuleSet = None }
                       """;
        var actual = value.TooString(TooStringMethod.Reflection);

        TestContext.Progress.WriteLine(actual);
        
        Assert.That(
            value
                .TooString(TooStringMethod.Reflection)
                .RegexReplaceKnownRuntimeVariableValues(),
            
            Is.EqualTo(expected.RegexReplaceKnownRuntimeVariableValues())
        );
    }


    [Test]
    public void GivenAnUnJsonableReflectionType_Module()
    {
        var value = typeof(Type)
            .GetMethods(BindingFlags.Instance|BindingFlags.Public)
            .First(m=>m.Name=="GetMethods")
            .Module;

        var expected = """
                       { MDStreamVersion = 131072, FullyQualifiedName = /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/System.Private.CoreLib.dll, ModuleVersionId = {  }, MetadataToken = 1, ScopeName = System.Private.CoreLib.dll, Name = System.Private.CoreLib.dll, Assembly = { CodeBase = file:///usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/System.Private.CoreLib.dll, FullName = System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, EntryPoint = null, DefinedTypes = [], IsCollectible = False, ManifestModule = System.Private.CoreLib.dll, ReflectionOnly = False, Location = /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/System.Private.CoreLib.dll, ImageRuntimeVersion = v4.0.30319, GlobalAssemblyCache = False, HostContext = 0, IsDynamic = False, ExportedTypes = [], IsFullyTrusted = True, CustomAttributes = System.Collections.ObjectModel.ReadOnlyCollection`1[System.Reflection.CustomAttributeData], EscapedCodeBase = file:///usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/System.Private.CoreLib.dll, Modules = [], SecurityRuleSet = None }, ModuleHandle = { MDStreamVersion = 131072 }, CustomAttributes = { Count = 2, Item = "cantretrievevalue" } }
                       """;
        
        var actual = value.TooString(TooStringMethod.Reflection);

        TestContext.Progress.WriteLine(actual);

        Assert.That(
            value.TooString(TooStringMethod.Reflection)
                .RegexReplaceKnownRuntimeVariableValues(),
            Is.EqualTo(
                expected.RegexReplaceKnownRuntimeVariableValues()));
    }
    
}
