<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Log.Assert.Tests" />
  </ItemGroup>
  <ItemGroup Condition=" $([System.Text.RegularExpressions.Regex]::IsMatch( '$(TargetFramework)', 'net[891].+' )) ">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup Condition=" $([System.Text.RegularExpressions.Regex]::IsMatch( '$(TargetFramework)', 'net[67].+' )) ">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
  </ItemGroup>
  <PropertyGroup>
    <AssemblyVersion>0.1</AssemblyVersion>
    <AssemblyFileVersion>0.1</AssemblyFileVersion>
    <PackageVersion>0.1</PackageVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Title>Log.Assert( it is "A better style of application logging" ).</Title>
    <PackageDescription><![CDATA[Log.Assert is a better style of application logging.
```
log.Member();
log.PreconditionNotNull(target);

var graphemes = new StringInfo(target??"");
log.Assert(graphemes.LengthInTextElements > 0);

log.Precondition(0 <= guess && guess <= graphemes.LengthInTextElements);

log.ExceptionAndThrowIf(
    graphemes.SubstringByTextElements(guess,1) is "💥",
    new ApplicationException("bang!"));

var remainder = Remove(graphemes,guess);
log.DebugIf(remainder.Length == 0,helpfulInformation: "TBC:is this permitted?");
log.If(graphemes.LengthInTextElements > 0,
          helpfulInformation: (target,guess,graphemes.LengthInTextElements),
          label: "Remaining after Removal");

log.PreconditionNotNull(target);
log.Postcondition(remainder.Length < target.Length);
log.Member(remainder);
return remainder;
```
## What is Logged?
 
- All methods log the current Method or Member name.
- Assertions, Pre-, and Post-Conditions log nothing at all if they pass.
- Assertions, Pre-, and Post-Conditions log the literal failed expression if they fail.
- log.If() logs nothing at all if the condition is false
- log.If() logs the literal condition expression if it is true
- All methods can log additional information, either auto-labelled or explicitly labelled.

```
log.Member()

log.Assert()
log.AssertNotNull()
log.Precondition()
log.PreconditionNotNull()
log.Postcondition()
log.PostconditionNotNull()

log.If()
log.IfNot()
```
and

```
log.InformationIf()
log.TraceIf()
log.DebugIf()
log.WarnIf()
log.ErrorIf()
log.CriticalIf()

log.InformationIfNot()
log.TraceIfNot()
log.DebugIfNot()
log.WarnIfNot()
log.ErrorIfNot()
log.CriticalIfNot()
log.ExceptionIf()
log.ExceptionAndThrowIf()
log.MemberException()
log.MemberExceptionThenThrow()
log.MemberCriticalExceptionThenExitProcessWithCode()
```
]]></PackageDescription>
    <PackageReleaseNotes>
      ChangeLog
      ---------
      0.1.0  First release
    </PackageReleaseNotes>
    <Copyright>(c) Chris F. Carroll, 2023-2026</Copyright>
    <PackageLicenseExpression>LGPL-2.1-or-later</PackageLicenseExpression>
    <Authors>Chris F Carroll</Authors>
    <Owners>Chris F Carroll</Owners>
    <PackageProjectUrl>https://github.com/chrisfcarroll/TestBase</PackageProjectUrl>
    <RepositoryUrl>https://github.com/chrisfcarroll/TestBase</RepositoryUrl>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <IncludeSymbols>true</IncludeSymbols>
    <PackageTags>stringify;serialization;tostring;debug;reflection;CallerArgumentExpression</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
