name: NugetPackAllCore.ps1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Pack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Show pwd
      run: |
        pwd
        ls -l . 
        ls -ld *
    - name: NugetPackAllCore.ps1
      run: ./NugetPackAllCore.ps1
      shell: pwsh
